### ISSUE TITLE
Fiddle example problem

### ISSUE THREAD

**Issue by njt1982** [Nijikokun/query-js#2]
Looks like, since you made the examples, JSFiddle have implemented MIME Type checking. GitHub is serving the JS as `text/plain` and not `text/js`.

Maybe you need to setup a gh-pages branch with the file in?

**Comment by Nijikokun** [comment]
Perhaps, this is just a historical repo at this point which is no longer maintained, I would suggest looking at URI.js

http://medialize.github.io/URI.js/

**Comment by njt1982** [comment]
Ooo thank you! I got my project working with your extension last night, but I'll take a look.

I needed something that could extract arrays from the query string (eg ?f[]=1&f[]=2). Your plugin worked perfectly, although it stumbled if the [] were encoded).

**Comment by Nijikokun** [comment]
Thanks, it should work, it just hasn't been touched in two years :P
