### ISSUE TITLE
AMD uh-oh

### ISSUE THREAD

**Issue by shmax** [nijikokun/query-js#3]
Hi there, thanks for putting together such a great library! Unfortunately, you've a small error on line 36:

```
context['define'] === 'function'
```

should be 
```
typeof context['define'] == 'function'
```

Also, I think (not sure, yet) that your call to define should only use the second argument; the first can be removed. 

I'll submit a PR this evening if you don't get to it by then. 

Thanks again!

**Comment by shmax** [comment]
@Nijikokun Anybody home?

**Comment by nijikokun** [comment]
This looks proper now~

**Comment by shmax** [comment]
Thanks much!
